import type { Locale } from '@/lib/i18n';

export type LegalContentLocale = 'en' | 'ru';
export type LegalPageKey = 'privacy' | 'terms' | 'cookies' | 'acceptable-use' | 'abuse' | 'contact';

type LegalSection = {
  title: string;
  body?: string[];
  items?: string[];
  highlight?: boolean;
};

type LegalPageContent = {
  title: string;
  description: string;
  sections: LegalSection[];
};

type LegalLocaleContent = {
  backHome: string;
  kicker: string;
  nav: Record<LegalPageKey, string>;
  pages: Record<LegalPageKey, LegalPageContent>;
};

export function getLegalLocale(locale: Locale): LegalContentLocale {
  return locale === 'ru' ? 'ru' : 'en';
}

export const legalContent: Record<LegalContentLocale, LegalLocaleContent> = {
  en: {
    backHome: 'Back to 10 Minute Mail',
    kicker: 'Legal and documentation',
    nav: {
      privacy: 'Privacy',
      terms: 'Terms',
      cookies: 'Cookies',
      'acceptable-use': 'Acceptable Use',
      abuse: 'Abuse',
      contact: 'Contact'
    },
    pages: {
      privacy: {
        title: 'Privacy Policy',
        description:
          'This policy explains how [PROJECT_NAME] processes data when you use the temporary email service at [DOMAIN]. Last updated: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'What the service does',
            body: [
              '[PROJECT_NAME] provides temporary email inboxes that can receive incoming messages for short-term use. The service is designed for quick testing, privacy protection, and reducing spam exposure, not for permanent or sensitive accounts.'
            ]
          },
          {
            title: 'Data we process',
            items: [
              'Temporary email address created by the service.',
              'Incoming email sender, recipient, subject, text body, and HTML body if provided.',
              'Timestamps such as mailbox creation time, expiry time, and message receipt time.',
              'Provider message ID or similar email-provider identifier used to avoid duplicate message storage.',
              'Server logs, IP address, user agent, request metadata, and security logs if generated by hosting, security tooling, or abuse-prevention features. These records are separate from mailbox message content.',
              'Cookies or localStorage preferences, including language preference, cookie consent choice, and temporary session or UI preferences if used.'
            ]
          },
          {
            title: 'Why we process data',
            items: [
              'To provide temporary email inbox functionality.',
              'To display incoming messages to the user of a temporary mailbox.',
              'To prevent abuse, spam, fraud, phishing, and misuse of the service.',
              'To maintain security, debug issues, and improve service reliability.',
              'To show ads or partner offers if advertising is enabled.'
            ]
          },
          {
            title: 'Retention',
            body: [
              'Temporary inbox messages are designed to expire automatically with the mailbox. Mailbox data and related messages are deleted after expiry and cleanup. Server logs, security logs, abuse signals, rate-limit records, or similar operational records may be retained longer only when needed to prevent abuse, investigate misuse, protect the service, debug reliability issues, or comply with legal obligations.'
            ]
          },
          {
            title: 'Legal basis',
            body: [
              'In general terms, data is processed to provide the requested service functionality, to support legitimate security and abuse-prevention interests, and, where required by law, based on user consent for non-essential cookies, analytics, or advertising technologies.'
            ]
          },
          {
            title: 'Third-party services',
            items: [
              'Supabase may be used for database and storage functionality.',
              'Mailgun or another email provider may process inbound email messages.',
              'Vercel or another hosting provider may host the application and process request metadata.',
              'Advertising partners may process limited data if ads or partner offers are enabled.'
            ]
          },
          {
            title: 'User rights',
            body: [
              'Depending on where you live, you may have rights to access, delete, or correct personal data, object to or restrict certain processing, and withdraw consent for non-essential cookies, ads, or analytics where applicable. To make a request, contact [CONTACT_EMAIL].'
            ]
          },
          {
            title: 'Important warning',
            highlight: true,
            body: [
              'Do not use temporary email for sensitive accounts, banking, healthcare, government services, legal matters, password recovery, or important long-term access. Temporary mailboxes may expire, messages may be deleted, and access may not be recoverable.'
            ]
          },
          {
            title: 'Contact',
            body: ['Operator: [OPERATOR_NAME], [OPERATOR_ADDRESS]. For privacy requests or general questions, contact [CONTACT_EMAIL].']
          }
        ]
      },
      terms: {
        title: 'Terms of Service',
        description: 'These terms govern your use of [PROJECT_NAME] at [DOMAIN]. Last updated: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'Acceptance of terms',
            body: ['By accessing or using [PROJECT_NAME], you agree to these Terms of Service. If you do not agree, do not use the service.']
          },
          {
            title: 'Description of service',
            body: [
              '[PROJECT_NAME] provides receive-only temporary email addresses and inboxes for short-term receipt of messages. The service does not support sending email from temporary addresses. Mailboxes are temporary by design and may expire, be deleted, or become unavailable at any time.'
            ]
          },
          {
            title: 'No guarantees',
            body: [
              'We do not guarantee email delivery, inbox availability, message storage, uptime, privacy, or recovery of any mailbox or message. You are responsible for deciding whether a temporary inbox is appropriate for your use case.'
            ]
          },
          {
            title: 'User responsibility',
            body: ['You are responsible for how you use the service and for complying with applicable laws, third-party platform rules, and these terms.']
          },
          {
            title: 'Prohibited uses',
            items: [
              'Spam, fraud, phishing, impersonation, or account abuse.',
              'Malware delivery, credential theft, or attempts to compromise systems.',
              'Harassment, threats, illegal activity, or abuse of third-party services.',
              'Bypassing bans, rate limits, fraud controls, or security systems.',
              'Receiving highly sensitive data, including banking, healthcare, government, legal, or long-term account access information.'
            ]
          },
          {
            title: 'Enforcement',
            body: [
              'We may block access, rate limit traffic, delete mailboxes or messages, block domains, or preserve relevant operational or security records if available and necessary to protect the service, users, third parties, or legal compliance.'
            ]
          },
          {
            title: 'Ads and third-party links',
            body: [
              'The service may display ads, partner offers, or third-party links. We are not responsible for third-party websites, products, claims, or data practices.'
            ]
          },
          {
            title: 'Disclaimers and liability',
            body: [
              'The service is provided as is and as available, without warranties of any kind. To the maximum extent allowed by law, [OPERATOR_NAME] is not liable for lost messages, unavailable mailboxes, service interruptions, third-party actions, or damages arising from use of the service.'
            ]
          },
          {
            title: 'Changes and contact',
            body: [
              'We may update these terms from time to time. Continued use of the service after changes means you accept the updated terms. Questions can be sent to [CONTACT_EMAIL].'
            ]
          }
        ]
      },
      cookies: {
        title: 'Cookie Policy',
        description:
          'This policy explains how [PROJECT_NAME] may use cookies, localStorage, and similar browser storage. Last updated: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'What cookies and localStorage are',
            body: [
              'Cookies are small files stored by your browser. localStorage is browser storage that lets a site remember simple preferences on the same device. Both can be used to keep a service working, remember settings, or support analytics and advertising if those features are enabled.'
            ]
          },
          {
            title: 'Essential storage',
            items: [
              'Language preference, so the interface can stay in your selected language.',
              'Cookie consent choice, so the site can remember whether you accepted essential storage only or all optional storage.',
              'Temporary session or UI preferences if used, such as the current mailbox state on your device.'
            ]
          },
          {
            title: 'Optional cookies',
            body: [
              'Analytics cookies are not required for the basic inbox. They may be added later to understand reliability and usage. Advertising cookies or similar technologies may be added later if ads or partner offers are enabled. Non-essential cookies, analytics, and advertising technologies should require consent where legally required and should read the saved consent choice before loading.'
            ]
          },
          {
            title: 'Managing cookies',
            body: [
              'You can manage or delete cookies and site storage in your browser settings. Blocking some storage may reset preferences or affect parts of the user interface. For questions, contact [CONTACT_EMAIL].'
            ]
          }
        ]
      },
      'acceptable-use': {
        title: 'Acceptable Use Policy',
        description: 'This policy explains acceptable and forbidden use of [PROJECT_NAME] at [DOMAIN]. Last updated: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'Allowed use',
            items: [
              'Testing websites, applications, signup flows, and email delivery.',
              'Protecting privacy when a permanent email address is not needed.',
              'Avoiding spam in low-risk, short-term interactions.',
              'Temporary signups where the third-party service allows temporary email addresses.'
            ]
          },
          {
            title: 'Forbidden use',
            items: [
              'Fraud, phishing, spam, malware, credential theft, or impersonation.',
              'Illegal marketplaces, illegal activity, or attempts to hide unlawful conduct.',
              'Harassment, threats, stalking, or targeted abuse.',
              'Evading enforcement, bans, security checks, or fraud-prevention systems.',
              'Abuse of third-party services, account creation systems, trials, promotions, or rate limits.'
            ]
          },
          {
            title: 'Enforcement',
            body: [
              'We may block access, delete messages or mailboxes, rate limit requests, block domains, or report abuse where legally required. Enforcement decisions may be made using available security signals and operational records.'
            ]
          }
        ]
      },
      abuse: {
        title: 'Report Abuse',
        description:
          'Use this page to report suspected misuse of [PROJECT_NAME]. We review abuse reports as available and take action where appropriate.',
        sections: [
          {
            title: 'How to report abuse',
            body: ['Send abuse reports to [ABUSE_EMAIL]. Please include enough detail for us to identify the temporary mailbox, message, or activity involved.']
          },
          {
            title: 'What to include',
            items: [
              'The temporary email address involved.',
              'Date, time, and timezone of the incident.',
              'Screenshots or URLs showing the abuse, if available.',
              'Message headers or provider details, if available.',
              'A clear description of the suspected abuse and why it violates rules or law.'
            ]
          },
          {
            title: 'Possible actions',
            body: [
              'Where necessary, the service may remove content, delete messages, block mailboxes, block domains, rate limit traffic, preserve relevant operational or security records if available, or take other reasonable steps to reduce abuse. We do not promise a specific investigation result or guaranteed response time.'
            ]
          }
        ]
      },
      contact: {
        title: 'Contact',
        description: 'Use these contacts for general questions, abuse reports, and legal or privacy requests related to [PROJECT_NAME].',
        sections: [
          {
            title: 'Contact channels',
            items: ['General contact: [CONTACT_EMAIL]', 'Abuse reports: [ABUSE_EMAIL]', 'Legal and privacy requests: [CONTACT_EMAIL]']
          },
          {
            title: 'Before you send',
            highlight: true,
            body: [
              'Do not send sensitive personal documents unless they are necessary for your request. For abuse reports, include only the details needed to identify the relevant temporary email address, message, or activity.'
            ]
          },
          {
            title: 'Operator',
            body: ['Operator: [OPERATOR_NAME]. Address: [OPERATOR_ADDRESS]. Domain: [DOMAIN].']
          }
        ]
      }
    }
  },
  ru: {
    backHome: 'Назад к 10 Minute Mail',
    kicker: 'Правовые документы и справка',
    nav: {
      privacy: 'Политика конфиденциальности',
      terms: 'Условия использования',
      cookies: 'Политика cookies',
      'acceptable-use': 'Правила использования',
      abuse: 'Сообщить о нарушении',
      contact: 'Контакты'
    },
    pages: {
      privacy: {
        title: 'Политика конфиденциальности',
        description:
          'Эта политика объясняет, как [PROJECT_NAME] обрабатывает данные при использовании временной почты на [DOMAIN]. Последнее обновление: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'Что делает сервис',
            body: [
              '[PROJECT_NAME] предоставляет временные почтовые ящики для краткосрочного получения входящих писем. Сервис предназначен для тестирования, защиты приватности и снижения спама, а не для постоянных или чувствительных аккаунтов.'
            ]
          },
          {
            title: 'Какие данные обрабатываются',
            items: [
              'Временный email-адрес, созданный сервисом.',
              'Отправитель входящего письма, получатель, тема, текстовая часть и HTML-тело письма, если они доступны.',
              'Временные метки: создание ящика, срок действия и получение сообщения.',
              'Идентификатор сообщения провайдера или аналогичный ID, который помогает не сохранять дубликаты.',
              'Серверные журналы, IP-адрес, user agent, метаданные запросов и журналы безопасности, если они создаются хостингом, инструментами безопасности или функциями защиты от злоупотреблений. Эти записи отделены от содержимого писем.',
              'Cookies или localStorage-настройки, включая выбранный язык, выбор согласия на cookies и другие UI/сессионные предпочтения, если они используются.'
            ]
          },
          {
            title: 'Зачем данные обрабатываются',
            items: [
              'Чтобы предоставить функциональность временного почтового ящика.',
              'Чтобы отображать входящие письма пользователю временного ящика.',
              'Чтобы предотвращать злоупотребления, спам, мошенничество, фишинг и неправомерное использование сервиса.',
              'Чтобы поддерживать безопасность, исправлять ошибки и повышать надежность сервиса.',
              'Чтобы показывать рекламу или партнерские предложения, если они включены.'
            ]
          },
          {
            title: 'Срок хранения',
            body: [
              'Временные письма рассчитаны на автоматическое истечение срока действия вместе с ящиком. Данные ящика и связанные сообщения удаляются после истечения срока и очистки. Серверные журналы, журналы безопасности, признаки злоупотреблений, записи rate limiting и похожие операционные данные могут храниться дольше только для предотвращения злоупотреблений, расследования нарушений, защиты сервиса, диагностики надежности или выполнения закона.'
            ]
          },
          {
            title: 'Правовое основание',
            body: [
              'В общем виде данные обрабатываются для предоставления запрошенной функциональности сервиса, в законных интересах безопасности и предотвращения злоупотреблений, а также, где это требуется законом, на основании согласия для необязательных cookies, аналитики или рекламных технологий.'
            ]
          },
          {
            title: 'Сторонние сервисы',
            items: [
              'Supabase может использоваться для базы данных и хранения.',
              'Mailgun или другой email-провайдер может обрабатывать входящие письма.',
              'Vercel или другой хостинг-провайдер может размещать приложение и обрабатывать метаданные запросов.',
              'Рекламные партнеры могут обрабатывать ограниченные данные, если включены реклама или партнерские предложения.'
            ]
          },
          {
            title: 'Права пользователей',
            body: [
              'В зависимости от вашей страны вы можете иметь право на доступ, удаление или исправление персональных данных, возражение или ограничение обработки, а также отзыв согласия на необязательные cookies, рекламу или аналитику, где это применимо. Для запроса свяжитесь с [CONTACT_EMAIL].'
            ]
          },
          {
            title: 'Важное предупреждение',
            highlight: true,
            body: [
              'Не используйте временную почту для чувствительных аккаунтов, банковских, медицинских, государственных, юридических сервисов, восстановления паролей или важного долгосрочного доступа. Временные ящики могут истечь, письма могут быть удалены, а доступ может быть невозможно восстановить.'
            ]
          },
          {
            title: 'Контакты',
            body: ['Оператор: [OPERATOR_NAME], [OPERATOR_ADDRESS]. По вопросам приватности и общим вопросам пишите на [CONTACT_EMAIL].']
          }
        ]
      },
      terms: {
        title: 'Условия использования',
        description: 'Эти условия регулируют использование [PROJECT_NAME] на [DOMAIN]. Последнее обновление: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'Принятие условий',
            body: ['Используя [PROJECT_NAME], вы соглашаетесь с этими условиями. Если вы не согласны, не используйте сервис.']
          },
          {
            title: 'Описание сервиса',
            body: [
              '[PROJECT_NAME] предоставляет временные email-адреса и почтовые ящики только для краткосрочного получения сообщений. Сервис не поддерживает отправку писем с временных адресов. Ящики по своей природе временные и могут истекать, удаляться или становиться недоступными в любой момент.'
            ]
          },
          {
            title: 'Нет гарантий',
            body: [
              'Мы не гарантируем доставку писем, доступность ящика, хранение сообщений, бесперебойную работу, приватность или восстановление любого ящика или сообщения. Вы сами решаете, подходит ли временный ящик для вашего случая.'
            ]
          },
          {
            title: 'Ответственность пользователя',
            body: ['Вы отвечаете за то, как используете сервис, и обязаны соблюдать применимые законы, правила сторонних платформ и эти условия.']
          },
          {
            title: 'Запрещенное использование',
            items: [
              'Спам, мошенничество, фишинг, выдача себя за другого или злоупотребление аккаунтами.',
              'Распространение вредоносного ПО, кража учетных данных или попытки компрометации систем.',
              'Домогательства, угрозы, незаконная деятельность или злоупотребление сторонними сервисами.',
              'Обход банов, лимитов, антифрод-контролей или систем безопасности.',
              'Получение высокочувствительных данных, включая банковские, медицинские, государственные, юридические данные или данные долгосрочного доступа.'
            ]
          },
          {
            title: 'Применение правил',
            body: [
              'Мы можем блокировать доступ, ограничивать частоту запросов, удалять ящики или сообщения, блокировать домены или сохранять доступные операционные записи либо журналы безопасности, если это необходимо для защиты сервиса, пользователей, третьих лиц или соблюдения закона.'
            ]
          },
          {
            title: 'Реклама и сторонние ссылки',
            body: [
              'Сервис может показывать рекламу, партнерские предложения или сторонние ссылки. Мы не отвечаем за сторонние сайты, продукты, заявления или практики обработки данных.'
            ]
          },
          {
            title: 'Отказ от гарантий и ограничение ответственности',
            body: [
              'Сервис предоставляется как есть и по мере доступности, без каких-либо гарантий. В максимальной степени, разрешенной законом, [OPERATOR_NAME] не несет ответственности за потерянные письма, недоступные ящики, перебои сервиса, действия третьих лиц или ущерб, связанный с использованием сервиса.'
            ]
          },
          {
            title: 'Изменения и контакт',
            body: [
              'Мы можем периодически обновлять эти условия. Продолжение использования сервиса после изменений означает принятие обновленных условий. Вопросы можно отправлять на [CONTACT_EMAIL].'
            ]
          }
        ]
      },
      cookies: {
        title: 'Политика cookies',
        description:
          'Эта политика объясняет, как [PROJECT_NAME] может использовать cookies, localStorage и похожее браузерное хранилище. Последнее обновление: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'Что такое cookies и localStorage',
            body: [
              'Cookies — это небольшие файлы, которые хранит браузер. localStorage — это браузерное хранилище, позволяющее сайту запоминать простые настройки на том же устройстве. Они могут использоваться для работы сервиса, сохранения настроек, аналитики и рекламы, если такие функции включены.'
            ]
          },
          {
            title: 'Необходимое хранение',
            items: [
              'Выбор языка, чтобы интерфейс оставался на выбранном языке.',
              'Выбор согласия на cookies, чтобы сайт помнил, выбрали ли вы только необходимое хранение или все необязательные варианты.',
              'Временные сессионные или UI-настройки, если используются, например состояние текущего ящика на вашем устройстве.'
            ]
          },
          {
            title: 'Необязательные cookies',
            body: [
              'Аналитические cookies не нужны для базовой работы inbox. Они могут быть добавлены позже для понимания надежности и использования сервиса. Рекламные cookies или похожие технологии могут быть добавлены позже, если включены реклама или партнерские предложения. Необязательные cookies, аналитика и рекламные технологии должны требовать согласия там, где это требуется законом, и проверять сохраненный выбор согласия перед загрузкой.'
            ]
          },
          {
            title: 'Как управлять cookies',
            body: [
              'Вы можете управлять cookies и хранилищем сайта или удалять их в настройках браузера. Блокировка части хранилища может сбросить настройки или повлиять на элементы интерфейса. По вопросам пишите на [CONTACT_EMAIL].'
            ]
          }
        ]
      },
      'acceptable-use': {
        title: 'Правила использования',
        description: 'Эта политика объясняет разрешенное и запрещенное использование [PROJECT_NAME] на [DOMAIN]. Последнее обновление: [LAST_UPDATED_DATE].',
        sections: [
          {
            title: 'Разрешенное использование',
            items: [
              'Тестирование сайтов, приложений, регистраций и доставки писем.',
              'Защита приватности, когда постоянный email не нужен.',
              'Снижение спама в краткосрочных и низкорисковых ситуациях.',
              'Временные регистрации там, где сторонний сервис допускает временные email-адреса.'
            ]
          },
          {
            title: 'Запрещенное использование',
            items: [
              'Мошенничество, фишинг, спам, вредоносное ПО, кража учетных данных или выдача себя за другого.',
              'Незаконные площадки, незаконная деятельность или попытки скрыть противоправные действия.',
              'Домогательства, угрозы, преследование или целевые злоупотребления.',
              'Обход ограничений, банов, проверок безопасности или антифрод-систем.',
              'Злоупотребление сторонними сервисами, системами создания аккаунтов, пробными периодами, промоакциями или лимитами.'
            ]
          },
          {
            title: 'Применение правил',
            body: [
              'Мы можем блокировать доступ, удалять сообщения или ящики, ограничивать частоту запросов, блокировать домены или сообщать о злоупотреблениях там, где это требуется законом. Решения могут приниматься на основе доступных сигналов безопасности и операционных записей.'
            ]
          }
        ]
      },
      abuse: {
        title: 'Сообщить о нарушении',
        description:
          'Используйте эту страницу, чтобы сообщить о предполагаемом злоупотреблении [PROJECT_NAME]. Мы рассматриваем жалобы по мере возможности и принимаем меры, когда это уместно.',
        sections: [
          {
            title: 'Как сообщить о нарушении',
            body: ['Отправляйте жалобы на [ABUSE_EMAIL]. Укажите достаточно деталей, чтобы мы могли определить временный ящик, сообщение или активность.']
          },
          {
            title: 'Что включить в жалобу',
            items: [
              'Временный email-адрес, связанный с нарушением.',
              'Дату, время и часовой пояс инцидента.',
              'Скриншоты или URL, показывающие нарушение, если они доступны.',
              'Заголовки письма или данные провайдера, если они доступны.',
              'Понятное описание предполагаемого нарушения и почему оно нарушает правила или закон.'
            ]
          },
          {
            title: 'Возможные меры',
            body: [
              'При необходимости сервис может удалить контент, удалить сообщения, заблокировать ящики, заблокировать домены, ограничить запросы, сохранить доступные операционные записи или журналы безопасности, если это необходимо, или принять другие разумные меры для снижения злоупотреблений. Мы не обещаем конкретный результат расследования или гарантированное время ответа.'
            ]
          }
        ]
      },
      contact: {
        title: 'Контакты',
        description: 'Используйте эти контакты для общих вопросов, жалоб на нарушения, юридических запросов и запросов по приватности, связанных с [PROJECT_NAME].',
        sections: [
          {
            title: 'Каналы связи',
            items: ['Общие вопросы: [CONTACT_EMAIL]', 'Жалобы на нарушения: [ABUSE_EMAIL]', 'Юридические запросы и вопросы приватности: [CONTACT_EMAIL]']
          },
          {
            title: 'Перед отправкой',
            highlight: true,
            body: [
              'Не отправляйте чувствительные личные документы, если они не необходимы для вашего запроса. Для жалоб на нарушения указывайте только детали, нужные для определения соответствующего временного email-адреса, сообщения или активности.'
            ]
          },
          {
            title: 'Оператор',
            body: ['Оператор: [OPERATOR_NAME]. Адрес: [OPERATOR_ADDRESS]. Домен: [DOMAIN].']
          }
        ]
      }
    }
  }
};
